id: I3F274BF4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:06:05+00:00'
last_modified: '2022-06-09T04:39:01.529159+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159447
  title: འདུལ་བ་བློ་གསར་འཇུག་པའི་ཐེམ་སྐས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    4B2B:
      image_group_id: I2PD18951
      title: Volume 1 of 'dul ba blo gsar 'jug pa'i them skas
      total_pages: 544
      order: 1
      base_file: 4B2B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
