id: P008121
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD159447
  title: འདུལ་བ་བློ་གསར་འཇུག་པའི་ཐེམ་སྐས།
  author: ''
  volumes:
    539abe57ca7343488216ec521231c308:
      image_group_id: I2PD18951
      title: Volume 1 of 'dul ba blo gsar 'jug pa'i them skas
      volume_number: 1
      total_pages: 544
      base_file: v001.txt
