id: P008121
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159447
  title: འདུལ་བ་བློ་གསར་འཇུག་པའི་ཐེམ་སྐས།
  author: ''
  volumes:
    cde3a099edeb4db8bd84e52e864a838a:
      image_group_id: I2PD18951
      title: ''
      volume_number: 1
      total_pages: 544
ebook_metadata:
  title: འདུལ་བ་བློ་གསར་འཇུག་པའི་ཐེམ་སྐས།
  author: ''
  sku: P008121
  cover: cover.jpg
  layers:
  - pagination
